services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: bot_platform
      POSTGRES_PASSWORD: bot_platform
      POSTGRES_DB: bot_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_platform -d bot_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    image: "${USER_BOT_IMAGE:-user_bot_app}"
    build: .
    restart: unless-stopped
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "${USER_BOT_APP_HOST_PORT:-8000}:8000"

volumes:
  postgres_data:
